version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "3478:3478"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: